ExamenAWSMiguelRicoç/Models/Apuesta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Models
{
    [Table("APUESTAS")]
    public class Apuesta
    {
        [Key]

        [Column("IDAPUESTA")]
        public int IdApuesta { get; set; }
        [Column("USUARIO")]
        public string Usuario { get; set; }
        [Column("IDEQUIPOLOCAL")]
        public int IdEquipoLocal { get; set; }
        [Column("IDEQUIPOVISITANTE")]
        public int IdEquipoVisitante { get; set; }

        [Column("GOLESEQUIPOLOCAL")]
        public int GolesEquipoLocal { get; set; }
        [Column("GOLESEQUIPOVISITANTE")]
        public int GolesEquipoVisitante { get; set; }

    }
}

ExamenAWSMiguelRicoç/Models/Equipo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Models
{
    [Table("EQUIPOS")]
    public class Equipo
    {
        [Key]
        [Column("IDEQUIPO")]
        public int IdEquipo { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("CHAMPIONS")]
        public int Champions { get; set; }
        [Column("WEB")]
        public string Web { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
    }
}

ExamenAWSMiguelRicoç/Models/ErrorViewModel.cs
using System;

namespace ExamenAWSMiguelRicoç.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenAWSMiguelRicoç/Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Models
{

    [Table("JUGADORES")]
    public class Jugador
    {
        [Key]

        [Column("IDJUGADOR")]
        public int IdJugador { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("POSICION")]
        public string Posicion { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("IDEQUIPO")]
        public int IdEquipo { get; set; }
    }
}

ExamenAWSMiguelRicoç/Controllers/ApuestasController.cs
using ExamenAWSMiguelRicoç.Models;
using ExamenAWSMiguelRicoç.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Controllers
{
    public class ApuestasController : Controller {
        private RepositoryApuestas repo;
        public ApuestasController(RepositoryApuestas repo) {
            this.repo = repo;
        }
        public IActionResult Index() {
            return View(this.repo.GetApuestas());
        }
        [HttpGet]
        public IActionResult Create() {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Apuesta apuesta) {
            this.repo.CreateApuesta(apuesta);
            return RedirectToAction("Index");
        }
    }
}

ExamenAWSMiguelRicoç/Controllers/EquiposController.cs
using ExamenAWSMiguelRicoç.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Controllers { 
    public class EquiposController : Controller {
        private RepositoryApuestas repo;
        public EquiposController(RepositoryApuestas repo) {
            this.repo = repo;
        }
        public IActionResult Index() {
            return View(this.repo.GetEquipos());
        }
    }
}

ExamenAWSMiguelRicoç/Controllers/HomeController.cs
using ExamenAWSMiguelRicoç.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenAWSMiguelRicoç/Controllers/JugadoresController.cs
using ExamenAWSMiguelRicoç.Models;
using ExamenAWSMiguelRicoç.Repositories;
using ExamenAWSMiguelRicoç.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenAWSMiguelRicoç.Controllers
{
    public class JugadoresController : Controller {
        private RepositoryApuestas repo;
        private ServiceAWSS3 service;
        public JugadoresController(RepositoryApuestas repo, ServiceAWSS3 service) {
            this.repo = repo;
            this.service = service;
        }
        public IActionResult Jugadores(int idequipo) {
            Equipo equipo = this.repo.FindEquipo(idequipo);
            ViewData["EQUIPO"] = equipo;
            return View(this.repo.GetJugadoresByEquipo(idequipo));
        }
        public IActionResult Details(int id) { 
            return View(this.repo.FindJugador(id)); 
        }
        [HttpGet]
        public IActionResult Create(int idequipo) {
            Equipo equipo = this.repo.FindEquipo(idequipo);
            ViewData["EQUIPO"] = equipo;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Jugador jugador, IFormFile imagen) {
            string nombreFichero = jugador.Nombre + "." + imagen.FileName.Split(".")[1];
            //using (Stream stream = imagen.OpenReadStream()) {
            //    await this.service.UploadFileAsync(stream, nombreFichero);
            //}
            jugador.Imagen = nombreFichero;
            this.repo.CreateJugador(jugador);
            return RedirectToAction("Jugadores", new { idequipo = jugador.IdEquipo});
        }
    }
}

ExamenAWSMiguelRicoç/Views/Apuestas/Create.cshtml
@model ExamenAWSMiguelRicoç.Models.Apuesta

@{
    ViewData["Title"] = "Create";
}

<h1>Crear apuesta</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Equipo Local</label>
                <input type="hidden" asp-for="IdEquipoLocal" value="1" />
                <input type="text" value="Real Madrid" class="form-control" disabled/>
                <span asp-validation-for="IdEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Equipo Visitante</label>
                <input type="hidden" asp-for="IdEquipoVisitante" value="2" />
                <input type="text" value="Manchester City" class="form-control" disabled />
                <span asp-validation-for="IdEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Goles Local</label>
                <input asp-for="GolesEquipoLocal" class="form-control" />
                <span asp-validation-for="GolesEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Goles Visitante</label>
                <input asp-for="GolesEquipoVisitante" class="form-control" />
                <span asp-validation-for="GolesEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear apuesta" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver al listado</a>
</div>

ExamenAWSMiguelRicoç/Views/Apuestas/GetJugadores.cshtml
@model IEnumerable<ExamenAWSMiguelRicoç.Models.Jugador>

@{
    ViewData["Title"] = "GetJugadores";
}

<h1>GetJugadores</h1>

<p>
    <a class="nav-link text-dark" asp-area="" asp-controller="Apuestas" asp-action="NuevoJugador" asp-route-idequipo="@ViewData["IDEQUIPO"]">Nuevo Jugador</a></p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdJugador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEquipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdJugador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEquipo)
            </td>
            <td>
                
            </td>
        </tr>
}
    </tbody>
</table>

ExamenAWSMiguelRicoç/Views/Apuestas/Index.cshtml
@model IEnumerable<ExamenAWSMiguelRicoç.Models.Apuesta>

@{
    ViewData["Title"] = "Index";
}

<h1>Apuestas</h1>

<p>
    <a asp-action="Create">Crear nueva apuesta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                Goles Real Madrid
            </th>
            <th>
                Goles Manchester City
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdApuesta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesEquipoLocal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesEquipoVisitante)
            </td>
        </tr>
}
    </tbody>
</table>

ExamenAWSMiguelRicoç/Views/Apuestas/NuevaApuesta.cshtml
@model ExamenAWSMiguelRicoç.Models.Apuesta

@{
    ViewData["Title"] = "NuevaApuesta";
}

<h1>NuevaApuesta</h1>

<h4>Apuesta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NuevaApuesta">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdApuesta" class="control-label"></label>
                <input asp-for="IdApuesta" class="form-control" />
                <span asp-validation-for="IdApuesta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEquipoLocal" class="control-label"></label>
                <input asp-for="IdEquipoLocal" class="form-control" />
                <span asp-validation-for="IdEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEquipoVisitante" class="control-label"></label>
                <input asp-for="IdEquipoVisitante" class="form-control" />
                <span asp-validation-for="IdEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GolesEquipoLocal" class="control-label"></label>
                <input asp-for="GolesEquipoLocal" class="form-control" />
                <span asp-validation-for="GolesEquipoLocal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GolesEquipoVisitante" class="control-label"></label>
                <input asp-for="GolesEquipoVisitante" class="form-control" />
                <span asp-validation-for="GolesEquipoVisitante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenAWSMiguelRicoç/Views/Apuestas/NuevoJugador.cshtml
@model ExamenAWSMiguelRicoç.Models.Jugador

@{
    ViewData["Title"] = "NuevoJugador";

}

<h1>NuevoJugador</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NuevoJugador" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdJugador" class="control-label"></label>
                <input asp-for="IdJugador" class="form-control" />
                <span asp-validation-for="IdJugador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input type="file" asp-for="Imagen" name="file" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEquipo" class="control-label"></label>
                <input asp-for="IdEquipo" class="form-control"  value="@ViewData["IDEQUIPO"]"/>
                <span asp-validation-for="IdEquipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExamenAWSMiguelRicoç/Views/Equipos/Index.cshtml
@model IEnumerable<ExamenAWSMiguelRicoç.Models.Equipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Equipos</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEquipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Champions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Web)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdEquipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" height="200" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Champions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Web)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <a asp-controller="Jugadores" asp-action="Jugadores" asp-route-idequipo="@item.IdEquipo">Jugadores</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExamenAWSMiguelRicoç/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamenAWSMiguelRicoç/Views/Jugadores/Create.cshtml
@model ExamenAWSMiguelRicoç.Models.Jugador

@{
    ViewData["Title"] = "Create";
    Equipo equipo = (Equipo) ViewData["EQUIPO"];
}

<h1>Crear jugador</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input type="file" name="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Equipo</label>
                <input asp-for="IdEquipo" value="@equipo.IdEquipo" class="form-control" type="hidden"/>
                <input type="text" value="@equipo.Nombre" disabled class="form-control"/>
                <span asp-validation-for="IdEquipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear jugador" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="VerJugadoresByEquipo" asp-route-idequipo="@equipo.IdEquipo">Volver al listado</a>
</div>

ExamenAWSMiguelRicoç/Views/Jugadores/Details.cshtml
@model ExamenAWSMiguelRicoç.Models.Jugador

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdJugador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdJugador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Posicion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEquipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEquipo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Jugadores" asp-route-idequipo="@Model.IdEquipo">Volver al listado</a>
</div>

ExamenAWSMiguelRicoç/Views/Jugadores/Jugadores.cshtml
@model IEnumerable<ExamenAWSMiguelRicoç.Models.Jugador>

@{
    ViewData["Title"] = "VerJugadoresByEquipo";
    Equipo equipo = (Equipo)ViewData["EQUIPO"];
}

<h1>Jugadores  @equipo.Nombre</h1>

<p>
    <a asp-action="Create" asp-route-idequipo="@equipo.IdEquipo"> jugador</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdJugador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdJugador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
                <img src="https://s3-imagenes-examen-mrc.s3.amazonaws.com/@item.Imagen" height="200"/>
            </td>
            <td>
                <a asp-controller="Jugadores" asp-action="Details" asp-route-id="@item.IdJugador">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExamenAWSMiguelRicoç/Views/Jugadores/VerJugadoresByEquipo.cshtml
@model IEnumerable<ExamenAWSMiguelRicoç.Models.Jugador>

@{
    ViewData["Title"] = "VerJugadoresByEquipo";
    Equipo equipo = (Equipo)ViewData["EQUIPO"];
}

<h1>Jugadores del @equipo.Nombre <img src="@equipo.Imagen" height="200"/></h1>

<p>
    <a asp-action="Create" asp-route-idequipo="@equipo.IdEquipo">Crear jugador</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdJugador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdJugador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
                <img src="https://s3-imagenes-doctores-mrc.s3.amazonaws.com/@item.Imagen" height="200"/>
            </td>
            <td>
                <a asp-controller="Jugadores" asp-action="Details" asp-route-id="@item.IdJugador">Detalles</a>
            </td>
        </tr>
}
    </tbody>
</table>

ExamenAWSMiguelRicoç/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenAWSMiguelRicoç</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenAWSMiguelRicoç</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipos" asp-action="Index">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apuestas" asp-action="Index">Apuestas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExamenAWSMiguelRicoç - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>